name: cook
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+12
  sqflite: ^1.3.0 #stable version at the time of publishing this article
  path_provider: ^1.6.7 #stable version at the time of publishing this article
  flutter_bloc: ^6.1.3
  quiz_view: ^1.0.3
  cached_network_image: ^2.0.0
  cool_stepper: ^1.1.1
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #http: "0.11.3+17"
  http: ^0.12.2
  crypto: ^2.1.5
  rflutter_alert: ^1.1.0
  signature: ^3.2.0
  custom_radio_grouped_button: any
  flutter_string_encryption: ^0.3.1
  random_color: ^1.0.5
  provider: ^4.3.3
  fluttertoast: ^7.1.8
  # flutter_offline: ^2.0.0
  connectivity: ^3.0.2
  flutter_svg: ^0.19.3



dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   flutter_offline: ^2.0.0
#   connectivity: ^3.0.2
    
flutter:
  assets:
    - lib/images/
    - lib/images/noWifi.svg
    - lib/images/serverDown.svg

  uses-material-design: true
